<testsuite errors="0" failures="1" name="unittest.suite.TestSuite" tests="1" time="0.002">
  <testcase classname="__main__.qa_my_qpsk_demod_cb" name="test_001_t" time="0.0015">
    <failure type="exceptions.AssertionError">1 != 2
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/ubuntu/gr-tutorial/python/qa_my_qpsk_demod_cb.py", line 38, in test_001_t
    self.assertEqual(1,2)
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
    </failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
